version: '3.8'

services:
  angular-app:
    build: 
      context: ./angular-app
      dockerfile: Dockerfile
    image: felipe2p05/examen-angular-app:latest
    ports:
      - "4200:80"
    depends_on:
      - puente-tcp-ws
    networks:
      - app-network

  puente-tcp-ws:
    build: 
      context: ./puente-tcp-ws
      dockerfile: Dockerfile
    image: felipe2p05/examen-puente-ws:latest
    ports:
      - "8080:8080"
    environment:
      - TCP_HOST=servidor
      - TCP_PORT=12345
      - WS_PORT=8080
    depends_on:
      - servidor
    networks:
      - app-network

  servidor:
    build: 
      context: ./servidor
      dockerfile: Dockerfile
    image: felipe2p05/examen-servidor:latest
    ports:
      - "12345:12345"
    networks:
      - app-network

  mensajes-aleatorios:
    build:
      context: ./mensajesaleatorios
      dockerfile: Dockerfile
    image: felipe2p05/examen-mensajes-aleatorios:latest
    environment:
      - SERVER_HOST=servidor
      - SERVER_PORT=12345
    depends_on:
      - servidor
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 


    